version: 2
updates:
  # Bun
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"

  # Bundler (Ruby)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "ruby"

  # Cargo (Rust)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "rust"

  # Composer (PHP)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "php"

  # Dev containers
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "devcontainers"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"

  # Docker Compose
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker-compose"

  # .NET SDK
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "dotnet"

  # Hex (Elixir)
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "elixir"

  # Elm
  - package-ecosystem: "elm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "elm"

  # Git submodule
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "gitsubmodule"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github-actions"

  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "go"

  # Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "java"

  # Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "java"

  # npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"

  # NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "dotnet"

  # pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"

  # pip-compile
  - package-ecosystem: "pip-compile"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"

  # pipenv
  - package-ecosystem: "pipenv"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"

  # pnpm
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"

  # poetry
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"

  # pub (Dart/Flutter)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "dart"

  # Swift
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "swift"

  # Terraform
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "terraform"

  # Yarn
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"
