version: 2
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_labels:
      - "dependencies"
  - package_manager: "javascript"
    directory: "/frontend"
    update_schedule: "live"
    target_branch: "master"
    default_labels:
      - "dependencies"
