aws_access_key_id= P7Y88ELT8JOF9T1UCSJ3
aws_secret_access_key= TSeDT31yJTXVZe*450hgYthJqklNuJVEM#g*NifO
aws_session_token = F6*9CyYo5@v8kWlWdh#3Hfj8H!GB6QOy2G@dQy3IjL1RscgNE&aUbRIp8JW@8YmX1!VVM5ZuTsNCw5D@J3*W*!gu$%va4Esp8*#!#RprRjg01ekGV#Z2ejeM@7RW7do!